const Images = {
MainLogo: require("../assets/images/MainLogo.png"),
Emailicon: require("../assets/images/mail.png"),
passwordIcon: require("../assets/images/password.png"),
openEye: require("../assets/images/openEye.png"),
closeEye: require("../assets/images/closeEye.png"),
user: require("../assets/images/user2.png"),
drawer: require("../assets/images/drawer.png"),
MainLogoPng: require("../assets/images/MainLogoPng.png"),
notification: require("../assets/images/notification.png"),
home: require("../assets/images/home.png"),
B1: require("../assets/images/B1.jpg"),
B2: require("../assets/images/B2.jpg"),
B3: require("../assets/images/B3.jpg"),
B4: require("../assets/images/B4.jpg"),
B5: require("../assets/images/B5.jpg"),
B6: require("../assets/images/B6.jpg"),
search: require("../assets/images/search.png"),
P1: require("../assets/images/p1.jpg"),
P2: require("../assets/images/p2.jpg"),
P3: require("../assets/images/p3.jpg"),
P4: require("../assets/images/p4.jpg"),
P5: require("../assets/images/p5.jpg"),
P6: require("../assets/images/p6.jpg"),
P7: require("../assets/images/p7.jpg"),
P8: require("../assets/images/p8.jpg"),
P9: require("../assets/images/p9.jpg"),
profile: require("../assets/images/profile.png"),

};

export default Images;
